# Generated by Django 3.2.19 on 2023-06-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0002_alter_sensores_humedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturas',
            name='data_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
