# Generated by Django 3.2.19 on 2023-06-13 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0003_lecturas_data_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturas',
            name='data_updated',
        ),
    ]
