# Generated by Django 3.2.19 on 2023-06-13 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0004_remove_lecturas_data_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturas',
            name='data_created',
        ),
    ]
