# Generated by Django 3.2.19 on 2023-06-13 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0005_remove_lecturas_data_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturas',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
